#load packages-------------------
library(glasso)
# if (!require("bnlearn")) install.packages("bnlearn", repos = 'http://cran.us.r-project.org')
library(bnlearn)
# install.packages('~/Downloads/bnlearn_4.4.1.tar', repos = NULL, type = 'source')
# "https://artifactory.vertigo.stitchfix.com/artifactory/sf-cran/"
library(matrixcalc)
# install.packages("matrixcalc")
library(doParallel)
# install.packages("doParallel")
if (!require("lars")) install.packages("lars")
library(lars)
library(MASS)
library(Matrix)
# install.packages('~/Downloads/scalreg_1.0.1.tar', repos = NULL, type = 'source')
library(scalreg)
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)
# if (!require("emdbook")) install.packages("emdbook")
library(emdbook)
if (!require("xtable")) install.packages("xtable")
library(xtable)
if (!require("gplots")) install.packages("gplots")
library(gplots)
# library(profvis)
if (!require("magic")) install.packages("magic")
library(magic)
if (!require("glmnet")) install.packages("glmnet")
library(glmnet)
library(sparsebn)
library(igraph)
if (!require("tnet")) install.packages("tnet")
library(tnet)
# if (!require("pcalg")) install.packages("pcalg")
library(pcalg)
if (!require("graph")) install.packages("graph")
library(graph)
# install.packages("~/Downloads/pcalg_2.6-2.tar", repos = NULL, type = "source")
library(stringr)
# library(rJava)
# library(devtools)
# install_github("bd2kccd/r-causal")
library(rcausal)
library(dplyr)
if (!require("clusterGeneration")) install.packages("clusterGeneration")
library(clusterGeneration)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
registerDoParallel(cores = 8)

